profiles/urls.py
from django.urls import path, include
from .views import create_profile
from .views import profile_view
from . import views

app_name = 'profiles'

urlpatterns = [
    path('create_profile/', create_profile, name='create_profile'),
    # Other URL patterns for your project...

    path('profile.html', views.profile_view, name='profile_html'),
]

resumehub/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import path, include

# Customise admin headings
admin.site.site_header = "KisanMitra Admin"
admin.site.site_title = "KisanMitra Admin Portal"
admin.site.index_title = "Welcome to KisanMitra Admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    
    # Resume specific paths
    path('resumes/', include('resumes.urls')),

    # Account specific paths
    path('accounts/', include('accounts.urls')),
    
    path('qualities/', include('qualities.urls', namespace='qualities')),

    path('profiles/', include('profiles.urls')),
    path('technical_skills/',include('qualities.urls', namespace='technical_skills')),
    
    path('soft_skills/',include('qualities.urls', namespace='soft_skills')),

    path('profile.html', views.profile_view, name='profile_html'),

    path('dashboard.html', views.dashboard_view, name='dashboard_html'),

    path('signup.html', views.signup_view, name='signup_html'),

    path('create_profile/', views.create_profile, name='create_profile'),

    path('estore/', views.estore, name='estore'),

     path('rice/', views.rice, name='rice'),
    
    path('organicservice/', views.organicservice, name='organicservice'),

     path('maize/', views.maize, name='maize'),
     path('wheat/', views.wheat, name='wheat'),
     path('sugar/', views.sugar, name='sugar'),
     path('bajra/', views.bajra, name='bajra'),
     path('tomato/', views.tomato, name='tomato'),
     path('subsidy/', views.subsidy, name='subsidy'),
]

resumes/urls.py
from django.urls import path, include
from . import views

app_name = 'resumes'

urlpatterns= [

    # All resumes
    path('', views.resumes, name='resumes'),

    # Individual resume
    path('<slug>', views.resume, name='resume'),

]

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
import uuid

# Create your models here.

class Profile(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    contact_number = models.CharField(verbose_name='contact_number', max_length=10, blank=True)
    bio = models.TextField(max_length=500, blank=True)
    address = models.CharField(max_length=100, blank=True)
    birth_date = models.TimeField(null=True, blank=True)
    linkedin_url = models.URLField(max_length=200, blank=True)  # LinkedIn URL
    instagram_url = models.URLField(max_length=200, blank=True)  # Instagram URL
    facebook_url = models.URLField(max_length=200, blank=True) # Facebook URL

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

profiles/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator
from .models import Profile
from .fields import PhoneNumberField

class UserProfileForm(forms.ModelForm):
    full_name = forms.CharField(label='Full Name', max_length=100)
    address = forms.CharField(label='Address', widget=forms.Textarea)
    age = forms.IntegerField(label='Age', validators=[MinValueValidator(0), MaxValueValidator(150)])
    phone_number = PhoneNumberField(label='Contact Number')
    email = forms.EmailField(label='Email Address')

    class Meta:
        model = Profile
        fields = ['full_name', 'address', 'age', 'phone_number', 'email']  # Rearrange fields

profiles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from resumes.models import Resume
from .forms import UserProfileForm
from qualities.forms import EducationForm
# Create your views here.


@login_required(login_url='accounts:login')
def create_profile(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('qualities:add_education')  # Redirect to the dashboard after successful form submission
    else:
        form = UserProfileForm()
    return render(request, 'create_profile.html', {'form': form})

def profile_view(request):
    return render(request, 'profile.html')

profiles/templates/create_profile.html
{% extends 'boiler.html' %}
{% block page_contents %}
{% load static %}
{% load widget_tweaks %}

<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2">User Profile Form</h1>
        <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
                <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>
            </div>
            <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1">
                <svg class="bi"><use xlink:href="#calendar3"></use></svg>
                This week
            </button>
        </div>
    </div>

    <div class="content">
        <form method="post">
            {% csrf_token %}
            <div class="field-wrapper">
                <label for="id_full_name">Full Name:</label>
                {% render_field form.full_name class="form-control" %}
            </div>

            <div class="field-wrapper">
                <label for="id_address">Address:</label>
                {% render_field form.address class="form-control" %}
            </div>

            <div class="field-wrapper">
                <label for="id_age">Age:</label>
                {% render_field form.age class="form-control" %}
            </div>

            <div class="field-wrapper">
                <label for="id_phone_number">Contact Number:</label>
                {% render_field form.phone_number class="form-control" %}
            </div>

            <div class="field-wrapper">
                <label for="id_email">Email Address:</label>
                {% render_field form.email class="form-control" %}
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</main>

<style>
    /* Custom CSS styles for form fields */
    .field-wrapper {
        margin-bottom: 20px;
    }

    label {
        font-weight: bold; /* Bold label text */
    }

    .form-control {
        border: 2px solid #3498db; /* Blue border */
        border-radius: 5px; /* Rounded corners */
        padding: 10px; /* Padding for spacing */
        font-size: 16px; /* Larger font size */
        color: #333; /* Dark text color */
        width: 100%; /* Full width */
        box-sizing: border-box; /* Include padding in width */
        transition: border-color 0.3s ease; /* Smooth transition */
    }

    .form-control:focus {
        border-color: #ff6f61; /* Red border when focused */
    }

    .btn-primary {
        background-color: #4caf50; /* Green background */
        color: white; /* White text color */
        padding: 10px 20px; /* Padding for button */
        border: none; /* No border */
        border-radius: 5px; /* Rounded corners */
        cursor: pointer; /* Cursor style */
        font-size: 16px; /* Font size */
        transition: background-color 0.3s ease; /* Smooth transition */
    }

    .btn-primary:hover {
        background-color: #45a049; /* Darker green on hover */
    }

    h1 {
        font-family: 'Arial', sans-serif; /* Custom font family */
        color: #4CAF50; /* Green text color */
        text-align: center; /* Centered text */
        margin-bottom: 30px; /* Bottom margin */
        text-shadow: 2px 2px 4px rgba(0,0,0,0.3); /* Text shadow */
    }

    h1:hover {
        color: #FF6F61; /* Red text color on hover */
    }
</style>
{% endblock %}