accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns= [
    #path('signup', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
]

resumehub/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import path, include

# Customise admin headings
admin.site.site_header = "KisanMitra Admin"
admin.site.site_title = "KisanMitra Admin Portal"
admin.site.index_title = "Welcome to KisanMitra Admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    
    # Resume specific paths
    path('resumes/', include('resumes.urls')),

    # Account specific paths
    path('accounts/', include('accounts.urls')),
    
    path('qualities/', include('qualities.urls', namespace='qualities')),

    path('profiles/', include('profiles.urls')),
    path('technical_skills/',include('qualities.urls', namespace='technical_skills')),
    
    path('soft_skills/',include('qualities.urls', namespace='soft_skills')),

    path('profile.html', views.profile_view, name='profile_html'),

    path('dashboard.html', views.dashboard_view, name='dashboard_html'),

    path('signup.html', views.signup_view, name='signup_html'),

    path('create_profile/', views.create_profile, name='create_profile'),

    path('estore/', views.estore, name='estore'),

     path('rice/', views.rice, name='rice'),
    
    path('organicservice/', views.organicservice, name='organicservice'),

     path('maize/', views.maize, name='maize'),
     path('wheat/', views.wheat, name='wheat'),
     path('sugar/', views.sugar, name='sugar'),
     path('bajra/', views.bajra, name='bajra'),
     path('tomato/', views.tomato, name='tomato'),
     path('subsidy/', views.subsidy, name='subsidy'),
]

resumes/urls.py
from django.urls import path, include
from . import views

app_name = 'resumes'

urlpatterns= [

    # All resumes
    path('', views.resumes, name='resumes'),

    # Individual resume
    path('<slug>', views.resume, name='resume'),

]

accounts/models.py
from django.db import models

# Create your models here.

frontend/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required

'''
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('user_pages:dashboard')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form':form})
'''

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('dashboard')

    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})


@login_required
def dashboard_view(request):
    return render(request, 'accounts/dashboard.html')

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

frontend/views.py
from django.shortcuts import render

# Create your views here.

frontend/templates/accounts/base.html
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Login to ResumeHub">
    <meta name="author" content="Vipul Kushwaha">
    <meta name="theme-color" content="rgba(31, 0, 59, 0.925)">

    <title>ResumeHub | Login</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'app_icon.png' %}" />

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <!--Fontawesome-->
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

</head>

<body style="padding-top: 1rem; ">
    <div class="container-fluid">

        <!--Start Content-->

        {% block page_contents %}
        {% endblock %}

        <!--End Content-->

    </div>
</body>

</html>

frontend/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block page_contents %}
{% load static %}

<div class="row">
    <div class="col-md-6 m-1 mx-auto p-3 shadow rounded">
        <div class="page-header">
            <div class="text-left">
                <h4><i class="fa fa-sign-in" aria-hidden="true"></i> KisanMitra Login</h4>
            </div>
        </div>

        <form class="site-form text-center" action="{% url 'accounts:login' %}" method="post">
            <img class="my-3 mx-auto" src="https://play-lh.googleusercontent.com/-iEJseYMZUMqefBP-uY_Ovznb-h4wOU5y1rO_9JfTzMEBg51IXkBl2WLgrssk8HgYQ=w600-h300-pc0xffffff-pd" alt="logo" width="220" height="100">
            <div class="col-md-4 mx-auto">
                {% csrf_token %}
                {{form}}
                {% if request.GET.next %}
                <input type="hidden" name="next" value="{{request.GET.next}}">
                {% endif %}
                <br>
                <input type="submit" class="btn btn-primary" value="Login">
            </div>
        </form>
        <div class="text-center">
            <a href="{% url 'home' %}" class="text-primary-sm">Back</a>
        </div>

        <footer class="pt-2 mx-auto text-center">
            <small><span class="text-muted">Licensed to SPIT | <a href="https://resumehub.spit.ac.in">KisanMitra</a> {% now "Y" %}</a>.
                </span>
            </small>
        </footer>
    </div>
</div>

{% endblock %}

frontend/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.84.0">
  <title>Signin Template · Bootstrap v5.0</title>
  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sign-in/">

  <!-- Bootstrap core CSS -->
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css" rel="stylesheet">

  <!-- Favicons -->
  <link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
  <link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
  <link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
  <link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
  <meta name="theme-color" content="#7952b3">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
    html,
body {
  height: 100%;
}

body {
  display: -ms-flexbox;
  display: -webkit-box;
  display: flex;
  -ms-flex-align: center;
  -ms-flex-pack: center;
  -webkit-box-align: center;
  align-items: center;
  -webkit-box-pack: center;
  justify-content: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
  </style>

  <!-- Custom styles for this template -->
</head>
<body class="text-center">
  <main class="form-signin">
    <form action="{% url 'create_profile' %}" method="post">
      {% csrf_token %}
      <img class="mb-4" src="https://play-lh.googleusercontent.com/-iEJseYMZUMqefBP-uY_Ovznb-h4wOU5y1rO_9JfTzMEBg51IXkBl2WLgrssk8HgYQ=w600-h300-pc0xffffff-pd" alt="" width="300" height="150">
      <h1 class="h3 mb-3 fw-normal">KisanMitra</h1>

      <div class="form-floating">
        <input type="email" class="form-control mb-3" id="floatingInput" placeholder="name@example.com">
        <!-- <label for="floatingInput">Email address</label> -->
      </div>
      <div class="form-floating">
        <input type="password" class="form-control mb-3" id="floatingPassword" placeholder="Password">
       <!-- <label for="floatingPassword">Password</label> -->
      </div>

      <button class="w-100 btn btn-lg btn-primary mb-3" type="submit" href="profiles/create_profile.html">Sign in</button>

      <div class="or-text">
        <pre> <font size=4.5> OR </font> </pre>
            <button class="btn btn-lg btn-primary bg-white text-dark w-100 mb-2" type="button">
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-google" viewBox="0 0 16 16" style="margin-right: 0.5rem;">
        <path d="M15.545 6.558a9.4 9.4 0 0 1 .139 1.626c0 2.434-.87 4.492-2.384 5.885h.002C11.978 15.292 10.158 16 8 16A8 8 0 1 1 8 0a7.7 7.7 0 0 1 5.352 2.082l-2.284 2.284A4.35 4.35 0 0 0 8 3.166c-2.087 0-3.86 1.408-4.492 3.304a4.8 4.8 0 0 0 0 3.063h.003c.635 1.893 2.405 3.301 4.492 3.301 1.078 0 2.004-.276 2.722-.764h-.003a3.7 3.7 0 0 0 1.599-2.431H8v-3.08z"/>
    </svg>
    Continue with Google
</button>

<button class="btn btn-lg btn-primary bg-white text-dark w-100 mb-3" type="button">
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-apple" viewBox="0 0 16 16" style="margin-right: 0.5rem;">
      <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516s1.52.087 2.475-1.258.762-2.391.728-2.43m3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422s1.675-2.789 1.698-2.854-.597-.79-1.254-1.157a3.7 3.7 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56s.625 1.924 1.273 2.796c.576.984 1.34 1.667 1.659 1.899s1.219.386 1.843.067c.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758q.52-1.185.473-1.282"/>
      <path d="M11.182.008C11.148-.03 9.923.023 8.857 1.18c-1.066 1.156-.902 2.482-.878 2.516s1.52.087 2.475-1.258.762-2.391.728-2.43m3.314 11.733c-.048-.096-2.325-1.234-2.113-3.422s1.675-2.789 1.698-2.854-.597-.79-1.254-1.157a3.7 3.7 0 0 0-1.563-.434c-.108-.003-.483-.095-1.254.116-.508.139-1.653.589-1.968.607-.316.018-1.256-.522-2.267-.665-.647-.125-1.333.131-1.824.328-.49.196-1.422.754-2.074 2.237-.652 1.482-.311 3.83-.067 4.56s.625 1.924 1.273 2.796c.576.984 1.34 1.667 1.659 1.899s1.219.386 1.843.067c.502-.308 1.408-.485 1.766-.472.357.013 1.061.154 1.782.539.571.197 1.111.115 1.652-.105.541-.221 1.324-1.059 2.238-2.758q.52-1.185.473-1.282"/>
  </svg>
  Continue with Apple
</button>

    </div>
    
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="remember-me"> Remember me
        </label>
      </div>
      
      <p class="mt-5 mb-3 text-muted">&copy; 2024</p>
    </form>
  </main>
</body>
</html>