qualities/urls.py
from django.urls import path
from . import views

app_name = 'qualities'

urlpatterns = [
    path('technical_skills/', views.technical_skills, name='technical_skills'),  # Route to view for technical skills
    path('soft_skills/', views.soft_skills, name='soft_skills'),  # Route to view for soft skills
    path('add_education/', views.add_education, name='add_education'),
    path('edit_education/<int:education_id>/', views.edit_education, name='edit_education'),
    path('education/delete/<int:education_id>/', views.delete_education, name='delete_education'),
]

resumehub/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import path, include

# Customise admin headings
admin.site.site_header = "KisanMitra Admin"
admin.site.site_title = "KisanMitra Admin Portal"
admin.site.index_title = "Welcome to KisanMitra Admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    
    # Resume specific paths
    path('resumes/', include('resumes.urls')),

    # Account specific paths
    path('accounts/', include('accounts.urls')),
    
    path('qualities/', include('qualities.urls', namespace='qualities')),

    path('profiles/', include('profiles.urls')),
    path('technical_skills/',include('qualities.urls', namespace='technical_skills')),
    
    path('soft_skills/',include('qualities.urls', namespace='soft_skills')),

    path('profile.html', views.profile_view, name='profile_html'),

    path('dashboard.html', views.dashboard_view, name='dashboard_html'),

    path('signup.html', views.signup_view, name='signup_html'),

    path('create_profile/', views.create_profile, name='create_profile'),

    path('estore/', views.estore, name='estore'),

     path('rice/', views.rice, name='rice'),
    
    path('organicservice/', views.organicservice, name='organicservice'),

     path('maize/', views.maize, name='maize'),
     path('wheat/', views.wheat, name='wheat'),
     path('sugar/', views.sugar, name='sugar'),
     path('bajra/', views.bajra, name='bajra'),
     path('tomato/', views.tomato, name='tomato'),
     path('subsidy/', views.subsidy, name='subsidy'),
]

resumes/urls.py
from django.urls import path, include
from . import views

app_name = 'resumes'

urlpatterns= [

    # All resumes
    path('', views.resumes, name='resumes'),

    # Individual resume
    path('<slug>', views.resume, name='resume'),

]

qualities/models.py
from django.db import models
import uuid
from django.utils.text import slugify
from django.contrib.auth.models import User

class Education(models.Model):
    """
    Holds the candidate's educational qualifications
    """
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    candidate = models.ForeignKey(User, verbose_name='Candidate', on_delete=models.CASCADE)
    
    # Education Level Choices
    primary = 'primary'
    middle_school = 'middle_school'
    high_school = 'high_school'
    higher_secondary =  'higher_secondary'
    graduation = 'graduation'
    post_graduation = 'post_graduation'
    doctorate = 'doctorate'
    post_doctorate = 'post_doctorate'
    diploma = 'diploma'
    course = 'course'
    other = 'other'

    EDUCATION_LEVEL_CHOICES = [
        (primary, 'primary'),
        (middle_school, 'middle_school'),
        (high_school, 'high_school'),
        (higher_secondary,  'higher_secondary'),
        (graduation, 'graduation'),
        (post_graduation, 'post_graduation'),
        (doctorate, 'doctorate'),
        (post_doctorate, 'post_doctorate'),
        (diploma, 'diploma'),
        (course, 'course'),
        (other, 'other'),
    ]

    education_level = models.CharField(verbose_name='Level', max_length=20, choices=EDUCATION_LEVEL_CHOICES)
    institute = models.CharField(verbose_name='Institute', max_length=150,)
    additional_info = models.TextField(verbose_name='Additional Info', null=True, blank=True)
    date_of_passing = models.DateTimeField(verbose_name='Date of Passing', null=True)
    pursuing = models.BooleanField(verbose_name='Pursuing', default=False)

    def __str__(self):
        return f'{self.education_level}-{self.institute}'


class Hobby(models.Model):
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    candidate = models.ForeignKey(User, verbose_name='Candidate', on_delete=models.CASCADE, null=True, default=None)
    name = models.CharField(verbose_name='Name', max_length=100, unique=True)
    slug = models.SlugField(verbose_name='Slug', null=True, blank=True)

    def save(self, *args, **kwargs):
        value = f'{self.name}'
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)
        

class TechnicalSkill(models.Model):
    """
    Model to represent technical skills.
    """
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    candidate = models.ForeignKey(User, verbose_name='Candidate', on_delete=models.CASCADE, related_name='technical_skills')
    name = models.CharField(verbose_name='Name', max_length=100, unique=True)
    slug = models.SlugField(verbose_name='Slug', null=True, blank=True)
    description = models.TextField(verbose_name='Description', blank=True, null=True)

    programming_language = 'programming_language'
    frameworks = 'frameworks'
    version_control = 'version_control'
    methodologies = 'methodologies'
    data_analysis = 'data_analysis'
    it_networking = 'it_networking'
    web_dev_design = 'web_dev_design'
    ai_ml = 'ai_ml'
    dbms = 'dbms'
    cloud_computing = 'cloud_computing'
    devops = 'devops'
    other = 'other'

    CATEGORY_CHOICES = [
        (programming_language, 'Programming Language'),
        (frameworks, 'Frameworks and Libraries'),
        (version_control, 'Version Control Systems'),
        (methodologies, 'Development Methodologies'),
        (data_analysis, 'Data Analysis and Analytics'),
        (it_networking, 'IT and Networking'),
        (web_dev_design, 'Web Development and Design'),
        (ai_ml, 'Machine Learning and Artificial Intelligence'),
        (dbms, 'Database Management'),
        (cloud_computing, 'Cloud Computing'),
        (devops, 'DevOps'),
        (other, 'Other')
    ]

    skill_type = 'technical'

    category = models.CharField(verbose_name='Category', max_length=25, choices=CATEGORY_CHOICES, default=other)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} - Technical Skill'

class SoftSkill(models.Model):
    """
    Model to represent soft skills.
    """
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    candidate = models.ForeignKey(User, verbose_name='Candidate', on_delete=models.CASCADE, related_name='soft_skills')
    name = models.CharField(verbose_name='Name', max_length=100, unique=True)
    slug = models.SlugField(verbose_name='Slug', null=True, blank=True)
    description = models.TextField(verbose_name='Description', blank=True, null=True)

    team_management = 'team_management'
    communication = 'communication'
    leadership = 'leadership'
    problem_solving = 'problem_solving'
    adaptability = 'adaptability'
    time_management = 'time_management'
    conflict_resolution = 'conflict_resolution'
    teamwork = 'teamwork'
    negotiation = 'negotiation'
    creativity = 'creativity'
    decision_making = 'decision_making'
    mentoring = 'mentoring'
    stress_management = 'stress_management'

    CATEGORY_CHOICES = [
        (team_management, 'Team Management'),
        (communication, 'Communication'),
        (leadership, 'Leadership'),
        (problem_solving, 'Problem Solving'),
        (adaptability, 'Adaptability'),
        (time_management, 'Time Management'),
        (conflict_resolution, 'Conflict Resolution'),
        (teamwork, 'Teamwork'),
        (negotiation, 'Negotiation'),
        (creativity, 'Creativity'),
        (decision_making, 'Decision Making'),
        (mentoring, 'Mentoring'),
        (stress_management, 'Stress Management')
    ]

    skill_type = 'soft'

    category = models.CharField(verbose_name='Category', max_length=25, choices=CATEGORY_CHOICES)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} - Soft Skill'

qualities/forms.py
from django import forms
from .models import TechnicalSkill, SoftSkill, Education

class TechnicalSkillForm(forms.ModelForm):
    name = forms.CharField(label='Name', max_length=100)
    description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'rows': 4}))
    category = forms.CharField(label='Category', max_length=25)

    class Meta:
        model = TechnicalSkill
        exclude = ['unique_id']  # Exclude the unique_id field

class SoftSkillForm(forms.ModelForm):
    name = forms.CharField(label='Name', max_length=100)
    description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'rows': 4}))
    category = forms.CharField(label='Category', max_length=25)

    class Meta:
        model = SoftSkill
        exclude = ['unique_id']  # Exclude the unique_id field

#class EducationForm(forms.ModelForm):
    #class Meta:
        #model = Education
        #fields = ['education_level', 'institute', 'additional_info', 'date_of_passing', 'pursuing']
from django import forms
from .models import Education

class EducationForm(forms.ModelForm):
    full_name = forms.CharField(label='Full Name', max_length=100)
    education_level = forms.ChoiceField(label='Education Level', choices=Education.EDUCATION_LEVEL_CHOICES)
    date_of_passing = forms.DateField(label='Date of Passing', widget=forms.TextInput(attrs={'class': 'datepicker'}))
    additional_info = forms.CharField(label='Additional Info', widget=forms.Textarea)
    pursuing = forms.BooleanField(label='Pursuing', required=False)  # Add this line
    


    class Meta:
        model = Education
        fields = ['full_name', 'institute', 'date_of_passing', 'additional_info', 'pursuing']  # Include the pursuing field

qualities/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import TechnicalSkill, SoftSkill
from .forms import TechnicalSkillForm, SoftSkillForm

@login_required(login_url='accounts:login')
def technical_skills(request):
    if request.method == 'POST':
        form = TechnicalSkillForm(request.POST)
        if form.is_valid():
            technical_skills = form.save(commit=False)
            technical_skills.candidate = request.user
            technical_skills.save()
            # Redirect to some view after saving the skill
            return redirect('technical_skills')
    else:
        form = TechnicalSkillForm()
    
    context = {
        'user': request.user,
        'form': form
    }
    return render(request, 'resumes/technical_skills.html', context)

@login_required(login_url='accounts:login')
def soft_skills(request):
    if request.method == 'POST':
        form = SoftSkillForm(request.POST)
        if form.is_valid():
            technical_skills = form.save(commit=False)
            technical_skills.candidate = request.user
            technical_skills.save()
            # Redirect to some view after saving the skill
            return redirect('soft_skills')
    else:
        form = SoftSkillForm()
    
    context = {
        'user': request.user,
        'form': form
    }
    return render(request, 'resumes/soft_skills.html', context)

    return render(request, 'resumes/skills.html', context)
# views.py in the qualities app

from .forms import EducationForm
from .models import Education
@login_required(login_url='accounts:login')
def add_education(request):
    if request.method == 'POST':
        form = EducationForm(request.POST)
        if form.is_valid():
            education = form.save(commit=False)
            education.candidate = request.user
            education.save()
            return redirect('qualities:add_education')  # Redirect back to the same page
    else:
        form = EducationForm()

    # Fetch the user's education entries
    user_educations = Education.objects.filter(candidate=request.user)
    education_level_choices = [choice[1] for choice in Education.EDUCATION_LEVEL_CHOICES]

    context = {
        'form': form,
        'education_level_choices': education_level_choices,
        'user_educations': user_educations
    }
    return render(request, 'qualities/add_education.html', context)

# views.py in the qualities app

from django.shortcuts import get_object_or_404

def edit_education(request, education_id):
    education_entry = get_object_or_404(Education, id=education_id)
    if request.method == 'POST':
        form = EducationForm(request.POST, instance=education_entry)
        if form.is_valid():
            form.save()
            return redirect('qualities:add_education')  # Redirect to the add education page
    else:
        form = EducationForm(instance=education_entry)
    
    context = {
        'form': form,
    }
    return render(request, 'edit_education.html', context)

def delete_education(request, education_id):
    education_entry = get_object_or_404(Education, id=education_id)
    education_entry.delete()
    return redirect('qualities:add_education')

qualities/templates/qualities/add_education.html
{% extends 'boiler.html' %}
{% block page_contents %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
        >
        <h1 class="h2">Resume Form</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Share
              </button>
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Export
              </button>
            </div>
            <button
              type="button"
              class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1"
            >
              <svg class="bi"><use xlink:href="#calendar3"></use></svg>
              This week
            </button>
          </div>
        </div>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Education</title>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- jQuery UI -->
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.datepicker-year').datepicker({
                changeYear: true,
                showButtonPanel: true,
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>
    <!-- Django tweaks -->
    {% load widget_tweaks %}
    <style>
        /* Custom CSS styles for form fields */
        label {
            font-weight: bold; /* Bold label text */
            display: block; /* Make labels block-level */
            margin-bottom: 5px; /* Add some spacing */
        }

        input[type="text"], textarea, select {
            border: 2px solid #3498db; /* Blue border */
            border-radius: 5px; /* Rounded corners */
            padding: 10px; /* Padding for spacing */
            font-size: 16px; /* Larger font size */
            color: #333; /* Dark text color */
            width: 100%; /* Full width */
            box-sizing: border-box; /* Include padding in width */
            transition: border-color 0.3s ease; /* Smooth transition */
            margin-bottom: 10px; /* Margin bottom for spacing */
        }

        input[type="text"]:focus, textarea:focus, select:focus {
            border-color: #ff6f61; /* Red border when focused */
        }

        button[type="submit"] {
            background-color: #4caf50; /* Green background */
            color: white; /* White text color */
            padding: 10px 20px; /* Padding for button */
            border: none; /* No border */
            border-radius: 5px; /* Rounded corners */
            cursor: pointer; /* Cursor style */
            font-size: 16px; /* Font size */
            transition: background-color 0.3s ease; /* Smooth transition */
        }
    
        button[type="submit"]:hover {
            background-color: #45a049; /* Darker green on hover */
        }

        h1 {
            font-family: 'Arial', sans-serif; /* Custom font family */
            color: #4CAF50; /* Green text color */
            text-align: center; /* Centered text */
            margin-bottom: 30px; /* Bottom margin */
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3); /* Text shadow */
        }

        h1:hover {
            color: #FF6F61; /* Red text color on hover */
        }
    </style>
</head>
<body>
    <h1>Add Education</h1>
    <form method="post">
        {% csrf_token %}
        <div class="field-wrapper">
            <label for="id_full_name">Full Name:</label>
            {% render_field form.full_name class="name" %}
        </div>

        <div class="field-wrapper">
            <label for="id_education_level">Education Level:</label>
            {% render_field form.education_level class="name" %}
        </div>

        <div class="field-wrapper">
            <label for="id_institute">Institute:</label>
            {% render_field form.institute class="name" %}
        </div>

        <div class="field-wrapper">
            <label for="id_date_of_passing">Date of Passing:</label>
            {% render_field form.date_of_passing class="datepicker-year name" %}
        </div>

        <div class="field-wrapper">
            <label for="id_additional_info">Additional Info:</label>
            {% render_field form.additional_info class="name" %}
        </div>

        <div class="field-wrapper">
            <label for="id_pursuing">Pursuing:</label>
            <input type="checkbox" id="id_pursuing" name="pursuing" {% if form.pursuing.value %}checked{% endif %}><br>
        </div>

        <button type="submit" class="name">Submit</button>
    </form>

    <h2>Your Education Entries</h2>
    <ul>
        {% for education in user_educations %}
            <li>{{ education.full_name }} - {{ education.institute }} - {{ education.date_of_passing }}</li>
            <li><a href="{% url 'qualities:edit_education' education.id %}">Edit</a></li>
            <li><a href="{% url 'qualities:delete_education' education.id %}">Delete</a></li>
            <br>
        {% empty %}
            <li>No education entries found.</li>
        {% endfor %}
    </ul>
</body>
</html>

{% endblock %}

qualities/templates/qualities/delete_education.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Delete Education</title>
</head>
<body>
    <h1>Delete Education</h1>
    <p>Are you sure you want to delete the education entry: {{ education }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Delete</button>
    </form>
</body>
</html>