accounts/urls.py
from django.urls import path, include
from . import views

app_name = 'accounts'

urlpatterns= [
    #path('signup', views.signup_view, name='signup'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
]

qualities/urls.py
from django.urls import path
from . import views

app_name = 'qualities'

urlpatterns = [
    path('technical_skills/', views.technical_skills, name='technical_skills'),  # Route to view for technical skills
    path('soft_skills/', views.soft_skills, name='soft_skills'),  # Route to view for soft skills
    path('add_education/', views.add_education, name='add_education'),
    path('edit_education/<int:education_id>/', views.edit_education, name='edit_education'),
    path('education/delete/<int:education_id>/', views.delete_education, name='delete_education'),
]

resumehub/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.urls import path, include

# Customise admin headings
admin.site.site_header = "KisanMitra Admin"
admin.site.site_title = "KisanMitra Admin Portal"
admin.site.index_title = "Welcome to KisanMitra Admin"


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    
    # Resume specific paths
    path('resumes/', include('resumes.urls')),

    # Account specific paths
    path('accounts/', include('accounts.urls')),
    
    path('qualities/', include('qualities.urls', namespace='qualities')),

    path('profiles/', include('profiles.urls')),
    path('technical_skills/',include('qualities.urls', namespace='technical_skills')),
    
    path('soft_skills/',include('qualities.urls', namespace='soft_skills')),

    path('profile.html', views.profile_view, name='profile_html'),

    path('dashboard.html', views.dashboard_view, name='dashboard_html'),

    path('signup.html', views.signup_view, name='signup_html'),

    path('create_profile/', views.create_profile, name='create_profile'),

    path('estore/', views.estore, name='estore'),

     path('rice/', views.rice, name='rice'),
    
    path('organicservice/', views.organicservice, name='organicservice'),

     path('maize/', views.maize, name='maize'),
     path('wheat/', views.wheat, name='wheat'),
     path('sugar/', views.sugar, name='sugar'),
     path('bajra/', views.bajra, name='bajra'),
     path('tomato/', views.tomato, name='tomato'),
     path('subsidy/', views.subsidy, name='subsidy'),
]

resumes/urls.py
from django.urls import path, include
from . import views

app_name = 'resumes'

urlpatterns= [

    # All resumes
    path('', views.resumes, name='resumes'),

    # Individual resume
    path('<slug>', views.resume, name='resume'),

]

frontend/models.py
from django.db import models

# Create your models here.

resumes/models.py
from django.db import models
import uuid
from django.utils.text import slugify
from django.contrib.auth.models import User
from qualities.models import Education
from qualities.models import TechnicalSkill,SoftSkill
from companies.models import Company


class TechnicalSkill(models.Model):
    programming_language = 'programming_language'
    frameworks = 'frameworks'
    version_control = 'version_control'
    methodologies = 'methodologies'
    data_analysis = 'data_analysis'
    it_networking = 'it_networking'
    web_dev_design = 'web_dev_design'
    ai_ml = 'ai_ml'
    dbms = 'dbms'
    cloud_computing = 'cloud_computing'
    devops = 'devops'
    other= 'other'

    CATEGORY_CHOICES = [
        (programming_language, 'Programming Language'),
        (frameworks, 'Frameworks and Libraries'),
        (version_control, 'Version Control Systems'),
        (methodologies, 'Development Methodologies'),
        (data_analysis, 'Data Analysis and Analytics'),
        (it_networking, 'IT and Networking'),
        (web_dev_design, 'Web Development and Design'),
        (ai_ml, 'Machine Learning and Artificial Intelligence'),
        (dbms, 'Database Management'),
        (cloud_computing, 'Cloud Computing'),
        (devops, 'DevOps'),
        (other, 'Other')
    ]

    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    candidate = models.ForeignKey(User, verbose_name='Candidate', on_delete=models.CASCADE, null=True, default=None)
    name = models.CharField(verbose_name='Name', max_length=100, unique=True)
    slug = models.SlugField(verbose_name='Slug', null=True, blank=True)
    category = models.CharField(verbose_name='Category', max_length=25, choices=CATEGORY_CHOICES, default=other)
    description = models.TextField(verbose_name='Description', blank=True, null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.name} - {self.skill_type} - {self.category}'



class SoftSkill(models.Model):
    team_management = 'team_management'
    communication = 'communication'
    leadership = 'leadership'
    problem_solving = 'problem_solving'
    adaptability = 'adaptability'
    time_management = 'time_management'
    conflict_resolution = 'conflict_resolution'
    teamwork = 'teamwork'
    negotiation = 'negotiation'
    creativity = 'creativity'
    decision_making = 'decision_making'
    mentoring = 'mentoring'
    stress_management = 'stress_management'

    CATEGORY_CHOICES = [
        (team_management, 'Team Management'),
        (communication, 'Communication'),
        (leadership, 'Leadership'),
        (problem_solving, 'Problem Solving'),
        (adaptability, 'Adaptability'),
        (time_management, 'Time Management'),
        (conflict_resolution, 'Conflict Resolution'),
        (teamwork, 'Teamwork'),
        (negotiation, 'Negotiation'),
        (creativity, 'Creativity'),
        (decision_making, 'Decision Making'),
        (mentoring, 'Mentoring'),
        (stress_management, 'Stress Management')
    ]

    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    candidate = models.ForeignKey(User, verbose_name='Candidate', on_delete=models.CASCADE, null=True, default=None)
    name = models.CharField(verbose_name='Name', max_length=100, unique=True)
    slug = models.SlugField(verbose_name='Slug', null=True, blank=True)
    category = models.CharField(verbose_name='Category', max_length=25, choices=CATEGORY_CHOICES, default='other')

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Resume(models.Model):
    """
    Holds Resume created by the candidate.
    """
    unique_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)
    name = models.CharField(verbose_name='name', max_length=100, blank=True)
    candidate = models.ForeignKey(User, verbose_name='Candidate', on_delete=models.SET_NULL, blank=True, null=True)
    slug = models.SlugField(verbose_name='slug', null=True, blank=True)
    description = models.TextField(verbose_name='Description', null=True, blank=True)
    summary = models.TextField(verbose_name='Summary', null=True, blank=True)
    
    # Education level choices
    education = models.PositiveSmallIntegerField('Educational qualifications (recent N, 0 for none)', default=0)

    # Options
    include_address = models.BooleanField(verbose_name='Include Address', default=True)
    include_contact_number = models.BooleanField(verbose_name='Include Contact Number', default=True)
    include_email_id = models.BooleanField(verbose_name='Include Email ID', default=True)
    target_company = models.ManyToManyField(Company, verbose_name='Target Companies')
    
    technical_skills = models.ManyToManyField(TechnicalSkill, verbose_name='Technical Skills', blank=True)
    soft_skills = models.ManyToManyField(SoftSkill, verbose_name='Soft Skills', blank=True)

    def save(self, *args, **kwargs):
        value = self.unique_id
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)


#     skills = models.TextField(verbose_name='Skills')
#     achievements = models.ManyToManyField(Achievement, verbose_name='Achievements')
#     projects = models.ManyToManyField(Project, verbose_name='Projects')
#     additional_sections = models.TextField(verbose_name='Additional Sections', blank=True)
#     work_experience = models.ForeignKey(WorkExperience, verbose_name='Work Experience', on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
            value = self.unique_id
            self.slug = slugify(value, allow_unicode=True)
            super().save(*args, **kwargs)

resumes/forms.py
from django import forms
from .models import Resume, TechnicalSkill, SoftSkill , Company

class ResumeForm(forms.ModelForm):
    technical_skills = forms.ModelMultipleChoiceField(
        queryset=TechnicalSkill.objects.all().order_by('category'),
        widget=forms.CheckboxSelectMultiple,
        required=False  # Set to True if technical skills are mandatory
    )

    soft_skills = forms.ModelMultipleChoiceField(
        queryset=SoftSkill.objects.all().order_by('category'),
        widget=forms.CheckboxSelectMultiple,
        required=False  # Set to True if soft skills are mandatory
    )
    
    target_company = forms.ModelMultipleChoiceField(
        queryset=Company.objects.all().order_by('name'),
        widget=forms.CheckboxSelectMultiple,
        required=False  # Set to True if soft skills are mandatory
    )

    class Meta:
        model = Resume
        fields = ['name','description','summary','target_company','technical_skills','soft_skills']

frontend/views.py
from django.shortcuts import render

# Create your views here.

resumes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from resumes.models import Resume
from .forms import ResumeForm

# Create your views here.

@login_required(login_url = 'accounts:login')
def resumes(request):
    if 'create' in request.GET:
        form = ResumeForm()
        context = {
            'user': request.user,
            'form': form
        }
        return render(request, 'resumes/create_resume.html', context)
    
    if request.method == 'POST':
        form = ResumeForm(request.POST)
        if form.is_valid():
            resume = form.save(commit=False)
            resume.candidate = request.user
            resume.save()
            return redirect('resumes:resume', slug=resume.slug)


    resumes = Resume.objects.filter(candidate=request.user)
    context = {
        'user':request.user,
        'resumes': resumes
    }
    return render(request, 'resumes/resumes.html', context)

@login_required(login_url = 'accounts:login')
def resume(request, slug):
    resume = Resume.objects.get(slug=slug)
    print(resume.candidate)
    context = {
        'resume': resume
    }
    return render(request, 'resumes/resume.html', context)

frontend/templates/resumes/create_resume.html
<!-- templates/create_resume.html -->

{% extends 'boiler.html' %}
{% block page_contents %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
        >
        <h1 class="h2">Resume Form</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Share
              </button>
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Export
              </button>
            </div>
            <button
              type="button"
              class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1"
            >
              <svg class="bi"><use xlink:href="#calendar3"></use></svg>
              This week
            </button>
          </div>
        </div>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Resume</title>
    <style>
        /* Custom CSS styles for form fields */
        .name{
            border: 2px solid #3498db; /* Blue border */
            border-radius: 5px; /* Rounded corners */
            padding: 10px; /* Padding for spacing */
            font-size: 16px; /* Larger font size */
            color:#fff; /* Dark text color */
            width: 100%; /* Full width */
            box-sizing: border-box; /* Include padding in width */
            transition: border-color 0.3s ease; /* Smooth transition */
            margin-bottom: 10px; /* Margin bottom for spacing */
        }

        input[type="text"]:focus, textarea:focus, input[type="checkbox"]:focus {
            border-color: #ff6f61; /* Red border when focused */
        }

        button[type="submit"] {
            background-color: #4caf50; /* Green background */
            color: white; /* White text color */
            padding: 10px 20px; /* Padding for button */
            border: none; /* No border */
            border-radius: 5px; /* Rounded corners */
            cursor: pointer; /* Cursor style */
            font-size: 16px; /* Font size */
            transition: background-color 0.3s ease; /* Smooth transition */
        }
    
        button[type="submit"]:hover {
            background-color: #45a049; /* Darker green on hover */
        }

        h1 {
            font-family: 'Arial', sans-serif; /* Custom font family */
            color: #4CAF50; /* Green text color */
            text-align: center; /* Centered text */
            margin-bottom: 30px; /* Bottom margin */
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3); /* Text shadow */
            transition: color 0.3s ease; /* Smooth transition */
        }

        h1:hover {
            color: #FF6F61; /* Red text color on hover */
        }
    </style>
</head>
<body>
    <h1>Create Resume for {{ user }}</h1>
    <form action="{% url 'create_profile' %}" method="post">
        {% csrf_token %}
        <div class="field-wrapper">
            <!-- Name field -->
            <label for="id_name">Name:</label><br>
            {% render_field form.name class="name" %}
        </div>
        <div class="field-wrapper">
            <!-- Description field -->
            <label for="id_description">Description:</label><br>
            {% render_field form.description class="name" %}
        </div>
        <div class="field-wrapper">
            <!-- Summary field -->
            <label for="id_summary">Summary:</label><br>
            {% render_field form.summary class="name" %}
        </div>
        <div class="field-wrapper">
            <!-- Target Company field -->
            <label for="id_target_company">Target Company:</label><br>
            {% render_field form.target_company class="name" %}
        </div>
        <div class="field-wrapper">
            <!-- Technical Skills field -->
            <label for="id_technical_skills">Technical Skills:</label><br>
            {% render_field form.technical_skills class="name" %}
        </div>
	<a href="{% url 'qualities:technical_skills' %}" class="btn btn-primary">Add New Technical Skill</a><br><br>
        <div class="field-wrapper">
            <!-- Soft Skills field -->
            <label for="id_soft_skills">Soft Skills:</label><br>
            {% render_field form.soft_skills class="name" %}
        </div>
        <a href="{% url 'qualities:soft_skills' %}" class="btn btn-primary">Add New Soft Skill</a><br>
        <!-- Add other fields similarly -->
        <br>
        <button type="submit">Submit</button>
    </form>
</body>
</html>
{% endblock %}
    

frontend/templates/resumes/resume.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>[Your Name] Resume</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
  <style>
    /* Add your custom CSS styles here (optional) */
    body {
      font-family: Arial, sans-serif;
      margin: 0; /* Remove default body margin */
      padding: 20px; /* Add some padding for mobile */
    }
    .container {
      max-width: 700px; /* Set a maximum width for responsiveness */
      margin: 0 auto; /* Center horizontally on all screen sizes */
    }
    h2 {
      margin-bottom: 5px;
    }
    h2 strong { /* Target only the bold text within h2 */
      font-size: 14px; /* Reduced font size for headings */
    }
    .experience, .education {
      margin-top: 0; /* Remove default margin-top */
    }
    .experience li, .education li {
      margin-bottom: 5px;
    }
  </style>
</head>
<body>

  <div class="container">
    <h1>[Your Name]</h1>
    <p>[Your Contact Information (Email, Phone Number, Location)]</p>

    <h2><strong>Profile Summary</strong></h2>
    <p>[A brief overview of your skills and experience relevant to the job you're applying for]</p>

    <h2><strong>Employment History</strong></h2>
    <ul>
      <li>
        <h3>[Job Title]</h3>
        <h4>[Company Name] - [Dates of Employment]</h4>
        <ul>
          <li>[Key responsibility or achievement]</li>
          <li>[Key responsibility or achievement]</li>
        </ul>
      </li>
      <li>
        <h3>[Job Title]</h3>
        <h4>[Company Name] - [Dates of Employment]</h4>
        <ul>
          <li>[Key responsibility or achievement]</li>
          <li>[Key responsibility or achievement]</li>
        </ul>
      </li>
    </ul>

    <h2><strong>Education</strong></h2>
    <ul>
      <li>
        <h3>[Qualification Name]</h3>
        <h4>[University/College Name] - [Dates of Attendance]</h4>
        <p>[Optional: Mention relevant coursework or achievements]</p>
      </li>
      <li>
        <h3>[Qualification Name]</h3>
        <h4>[University/College Name] - [Dates of Attendance]</h4>
        <p>[Optional: Mention relevant coursework or achievements]</p>
      </li>
    </ul>

    <h2><strong>Skills</strong></h2>
    <ul>
      <li>[Skill 1]</li>
      <li>[Skill 2]</li>
    </ul>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>

  <h2>Resume of user: {{user}}</h2>

  <form action="{% url 'accounts:logout' %}" method="post">
    {% csrf_token %}
    <button class="dropdown-item" type="submit">Sign out</button>
  </form>

</body>
</html>

frontend/templates/resumes/soft_skills.html
<!-- technical_skill_form.html -->

{% extends 'boiler.html' %}
{% block page_contents %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
        >
        <h1 class="h2">Soft Skill Form</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Share
              </button>
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Export
              </button>
            </div>
            <button
              type="button"
              class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1"
            >
              <svg class="bi"><use xlink:href="#calendar3"></use></svg>
              This week
            </button>
          </div>
        </div>
</head>
<body>

    <style>
        /* Custom CSS styles for form fields */
        .name {
            border: 2px solid #3498db; /* Blue border */
            border-radius: 5px; /* Rounded corners */
            padding: 10px; /* Padding for spacing */
            font-size: 16px; /* Larger font size */
            color: #333; /* Dark text color */
            width: 100%; /* Full width */
            box-sizing: border-box; /* Include padding in width */
            transition: border-color 0.3s ease; /* Smooth transition */
            margin-bottom: 10px; /* Margin bottom for spacing */
        }

        input[type="text"]:focus, textarea:focus, input[type="checkbox"]:focus {
            border-color: #ff6f61; /* Red border when focused */
        }

        button[type="submit"] {
            background-color: #4caf50; /* Green background */
            color: white; /* White text color */
            padding: 10px 20px; /* Padding for button */
            border: none; /* No border */
            border-radius: 5px; /* Rounded corners */
            cursor: pointer; /* Cursor style */
            font-size: 16px; /* Font size */
            transition: background-color 0.3s ease; /* Smooth transition */
        }
    
        button[type="submit"]:hover {
            background-color: #45a049; /* Darker green on hover */
        }

        h1 {
            font-family: 'Arial', sans-serif; /* Custom font family */
            color: #4CAF50; /* Green text color */
            text-align: center; /* Centered text */
            margin-bottom: 30px; /* Bottom margin */
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3); /* Text shadow */
            transition: color 0.3s ease; /* Smooth transition */
        }

        h1:hover {
            color: #FF6F61; /* Red text color on hover */
        }
    </style>
    <h1>Add you Soft Skills!</h1>
    <form   method="post">
        {% csrf_token %}
        <div class="field-wrapper">
            <label for="id_name">Name:</label><br>
            {% render_field form.name class="name" %}
        </div>
        <div class="field-wrapper">
            <label for="id_description">Description:</label><br>
            {% render_field form.description class="name" %}
        </div>
        <div class="field-wrapper">
            <label for="id_category">Category:</label><br>
            {% render_field form.category class="name" %}
        </div>
        <button type="submit">Submit</button>
    </form>
</body>
</html>
{% endblock %}

frontend/templates/resumes/subsidy.html
{% extends 'boiler.html' %}
{% block page_contents %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Government Schemes</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            background-color: black;
            color: #333;
            margin: 0;
            padding: 20px;
        }

        .scheme {
            background-color:#90EE90;
            padding: 20px;
            margin-bottom: 20px;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }

        .scheme h2 {
            color: #333;
        }

        .scheme p {
            margin-bottom: 10px;
        }

        .scheme-details {
            margin-left: 20px;
        }

        .apply-btn {
            display: inline-block;
            background-color: #007bff;
            color: #fff;
            padding: 8px 16px;
            border-radius: 5px;
            text-decoration: none;
            transition: background-color 0.3s ease;
            margin-top: 10px;
        }

        .apply-btn:hover {
            background-color: black;
        }
    </style>
</head>

<body>
    <div class="scheme">
        <h2>Central Sector Schemes</h2>
        <div class="scheme-details">
            <h3>1. Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)</h3>
            <p><strong>Purpose:</strong> To supplement financial needs of land-holding farmers.</p>
            <p><strong>Details:</strong> PM-KISAN transfers Rs. 6000/year in three installments via DBT to farmers.</p>
            <p><strong>Impact:</strong> Rs. 2.81 lakh crores transferred to over 11 crore beneficiaries.</p>
            <a href="#" class="apply-btn">Apply Now</a>
        </div>

        <div class="scheme-details">
            <h3>2. Pradhan Mantri Kisan MaanDhan Yojana (PM-KMY)</h3>
            <p><strong>Purpose:</strong> Provide security to vulnerable farmer families.</p>
            <p><strong>Details:</strong> Contributory scheme with monthly subscriptions and pension benefits.</p>
            <p><strong>Enrollment:</strong> 23.38 lakh farmers have enrolled.</p>
            <a href="#" class="apply-btn">Apply Now</a>
        </div>

        <!-- Add apply button for each scheme -->
        
        <div class="scheme-details">
            <h3>3. Pradhan Mantri Fasal Bima Yojana (PMFBY)</h3>
            <p><strong>Purpose:</strong> Provide crop insurance cover to farmers.</p>
            <p><strong>Details:</strong> Offers comprehensive risk cover against natural risks.</p>
            <p><strong>Impact:</strong> 5549.40 lakh farmer applications insured; Rs. 150589.10 crore paid as claim.</p>
            <a href="#" class="apply-btn">Apply Now</a>
        </div>

        <div class="scheme-details">
            <h3>4. Modified Interest Subvention Scheme (MISS)</h3>
            <p><strong>Purpose:</strong> Provide concessional agri-loans to farmers.</p>
            <p><strong>Details:</strong> Interest rate of 7% per annum; additional subvention for prompt repayment.</p>
            <p><strong>Impact:</strong> 465.42 lakh new KCC applications sanctioned with credit limit of Rs. 5,69,974 crore.</p>
            <a href="#" class="apply-btn">Apply Now</a>
        </div>

        <div class="scheme-details">
            <h3>5. Agriculture Infrastructure Fund (AIF)</h3>
            <p><strong>Purpose:</strong> Address infrastructure gaps and mobilize investment in agriculture.</p>
            <p><strong>Details:</strong> Rs. 1 Lakh Crore fund with interest subvention and credit guarantee support.</p>
            <p><strong>Impact:</strong> Rs. 33.209 Crores sanctioned for 44,912 projects, mobilizing Rs. 56.471 Crores investment.</p>
            <a href="#" class="apply-btn">Apply Now</a>
        </div>

        <div class="scheme-details">
            <h3>6. Formation & Promotion of new 10,000 FPOs</h3>
            <p><strong>Purpose:</strong> Promote and support Farmer Producer Organizations.</p>
            <p><strong>Details:</strong> Financial assistance, equity grant, credit guarantee, and training support.</p>
            <p><strong>Impact:</strong> Total 7,774 FPOs registered under the scheme.</p>
            <a href="#" class="apply-btn">Apply Now</a>
        </div>

        <div class="scheme-details">
            <h3>7. National beekeeping and Honey Mission (NBHM)</h3>
            <p><strong>Purpose:</strong> Promote scientific beekeeping and honey production.</p>
            <p><strong>Details:</strong> Approval of honeybees as 5th input for agriculture, establishment of testing labs, and online registration portal.</p>
            <p><strong>Impact:</strong> 23 lakhs bee colonies registered; 160 projects sanctioned under NBHM.</p>
            <a href="#" class="apply-btn">Apply Now</a>
        </div>
    </div>
</body>

</html>
{% endblock %}

frontend/templates/resumes/technical_skills.html
<!-- technical_skill_form.html -->

{% extends 'boiler.html' %}
{% block page_contents %}
{% load widget_tweaks %}
<!DOCTYPE html>
<html lang="en">
<head>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
        >
        <h1 class="h2">Technical Skill Form</h1>
          <div class="btn-toolbar mb-2 mb-md-0">
            <div class="btn-group me-2">
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Share
              </button>
              <button type="button" class="btn btn-sm btn-outline-secondary">
                Export
              </button>
            </div>
            <button
              type="button"
              class="btn btn-sm btn-outline-secondary dropdown-toggle d-flex align-items-center gap-1"
            >
              <svg class="bi"><use xlink:href="#calendar3"></use></svg>
              This week
            </button>
          </div>
        </div>
</head>
<body>

    <style>
        /* Custom CSS styles for form fields */
        .name {
            border: 2px solid #3498db; /* Blue border */
            border-radius: 5px; /* Rounded corners */
            padding: 10px; /* Padding for spacing */
            font-size: 16px; /* Larger font size */
            color: #333; /* Dark text color */
            width: 100%; /* Full width */
            box-sizing: border-box; /* Include padding in width */
            transition: border-color 0.3s ease; /* Smooth transition */
            margin-bottom: 10px; /* Margin bottom for spacing */
        }

        input[type="text"]:focus, textarea:focus, input[type="checkbox"]:focus {
            border-color: #ff6f61; /* Red border when focused */
        }

        button[type="submit"] {
            background-color: #4caf50; /* Green background */
            color: white; /* White text color */
            padding: 10px 20px; /* Padding for button */
            border: none; /* No border */
            border-radius: 5px; /* Rounded corners */
            cursor: pointer; /* Cursor style */
            font-size: 16px; /* Font size */
            transition: background-color 0.3s ease; /* Smooth transition */
        }
    
        button[type="submit"]:hover {
            background-color: #45a049; /* Darker green on hover */
        }

        h1 {
            font-family: 'Arial', sans-serif; /* Custom font family */
            color: #4CAF50; /* Green text color */
            text-align: center; /* Centered text */
            margin-bottom: 30px; /* Bottom margin */
            text-shadow: 2px 2px 4px rgba(0,0,0,0.3); /* Text shadow */
            transition: color 0.3s ease; /* Smooth transition */
        }

        h1:hover {
            color: #FF6F61; /* Red text color on hover */
        }
    </style>
    <h1>Add you Technical Skills!</h1>
    <form   method="post">
        {% csrf_token %}
        <div class="field-wrapper">
            <label for="id_name">Name:</label><br>
            {% render_field form.name class="name" %}
        </div>
        <div class="field-wrapper">
            <label for="id_description">Description:</label><br>
            {% render_field form.description class="name" %}
        </div>
        <div class="field-wrapper">
            <label for="id_category">Category:</label><br>
            {% render_field form.category class="name" %}
        </div>
        <button type="submit">Submit</button>
    </form>
</body>
</html>
{% endblock %}